[package]
edition = "2021"
build = "src/build.rs"
name = "pls"
version = "1.3.1"
authors = ["The Operator <op@gmail.com>"]

description = "A simple Bash-like Unix shell."
repository = "https://github.com"
keywords = ["shell", "unix"]
categories = ["command-line-utilities", "command-line-interface", "development-tools"]
license = "MIT"

[profile.release]
lto = true
strip = true

[lib]
name = "pls"
path = "src/lib.rs"

[[bin]]
name = "pls"
doc = false

[dependencies.errno]
version = "0.3.14"
path = "crates/errno-0.3.14"

[dependencies.glob]
version = "0.3.3"
path = "crates/glob-0.3.3"

[dependencies.nix]
version = "0.31"
features = ["fs", "process", "signal"]
path = "crates/nix-0.31.2"

[dependencies.regex]
version = "1.12.3"
path = "crates/regex-1.12.3"

[dependencies.lineread]
version = "0.7.4"
path = "crates/lineread-0.7.4"

[dependencies.structopt]
version = "0.3.26"
path = "crates/structopt-0.3.26"
default-features = false

[dependencies.uuid]
version = "1.23.1"
path = "crates/uuid-1.23.1"
features = ["serde", "v4"]

#[dependencies.yaml-rust]
#path = "crates/yaml-rust-0.4.5"
#version = "0.4.5"

[dependencies.over]
path = "crates/over-0.6.6"
version = "0.6.6"

[dependencies.pest]
version = "2.8.6"
path = "crates/pest-2.8.6"

[dependencies.pest_derive]
version = "2.8.6"
path = "crates/pest_derive-2.8.6"

[dependencies.exec]
version = "0.3.1"
path = "crates/exec-0.3.1"


[dependencies.lazy_static]
version = "1.5.0"
path = "crates/lazy_static-1.5.0"

[dependencies.libc]
version = "0.2.185"
path = "crates/libc-0.2.185"

[dependencies.clap]
version = "4.5"
default-features = false
features = ["std", "derive", "help"]
path = "crates/clap-4.6.1"

[dependencies.rusqlite]
version = "0.38"
path = "crates/rusqlite-0.38.0"
features = ["bundled"]

[dependencies.time]
version = "0.3"
path = "crates/time-0.3.47"
features = ["local-offset"]


